export const initialWeeks = [
  {
    id: 1,
    title: 'Blitz Week',
    startDate: '2025-01-06',
    startTime: '10:00',
    active: true,
    displaySection: 'past',
    scoringSystem: 'partial',
    problems: [
      {
        id: 101, name: 'Two Sum', difficulty: 'Easy', maxScore: 100,
        timeLimit: 1.0, spaceLimit: 256,
        description: 'Given an array of integers and a target, return indices of the two numbers that add up to target.',
        inputFormat: 'First line: n\nSecond line: n integers\nThird line: target',
        outputFormat: 'Two space-separated indices',
        constraints: '2 ≤ n ≤ 10^4\n-10^9 ≤ nums[i] ≤ 10^9',
        examples: [{ input: '4\n2 7 11 15\n9', output: '0 1', explanation: 'nums[0] + nums[1] = 9' }],
        testCases: [{ id: 1, input: '4\n2 7 11 15\n9', output: '0 1', score: 50 }],
        languages: ['CPP', 'JAVA', 'PYTHON'],
        multipleSolution: false,
        validatorCode: '',
      },
      {
        id: 102, name: 'Longest Substring Without Repeating', difficulty: 'Medium', maxScore: 150,
        timeLimit: 2.0, spaceLimit: 256,
        description: 'Find the length of the longest substring without repeating characters.',
        inputFormat: 'A single string s',
        outputFormat: 'An integer',
        constraints: '0 ≤ s.length ≤ 5×10^4',
        examples: [{ input: 'abcabcbb', output: '3', explanation: 'abc is the longest' }],
        testCases: [],
        languages: ['CPP', 'JAVA', 'PYTHON'],
        multipleSolution: false,
        validatorCode: '',
      },
      {
        id: 103, name: 'Merge Intervals', difficulty: 'Medium', maxScore: 175,
        timeLimit: 2.0, spaceLimit: 256,
        description: 'Given an array of intervals, merge all overlapping intervals.',
        inputFormat: 'First line: n\nNext n lines: two integers start end',
        outputFormat: 'Merged intervals, one per line',
        constraints: '1 ≤ n ≤ 10^4\n0 ≤ start ≤ end ≤ 10^4',
        examples: [{ input: '4\n1 3\n2 6\n8 10\n15 18', output: '1 6\n8 10\n15 18', explanation: '1-3 and 2-6 overlap' }],
        testCases: [],
        languages: ['CPP', 'JAVA', 'PYTHON'],
        multipleSolution: false,
        validatorCode: '',
      },
      {
        id: 104, name: 'Maximum Subarray', difficulty: 'Hard', maxScore: 200,
        timeLimit: 1.5, spaceLimit: 256,
        description: 'Find the contiguous subarray with the largest sum.',
        inputFormat: 'First line: n\nSecond line: n integers',
        outputFormat: 'The maximum sum',
        constraints: '1 ≤ n ≤ 10^5\n-10^4 ≤ nums[i] ≤ 10^4',
        examples: [{ input: '9\n-2 1 -3 4 -1 2 1 -5 4', output: '6', explanation: '[4,-1,2,1] has the largest sum' }],
        testCases: [],
        languages: ['CPP', 'JAVA', 'PYTHON'],
        multipleSolution: false,
        validatorCode: '',
      },
      {
        id: 105, name: 'Word Ladder', difficulty: 'Hard', maxScore: 250,
        timeLimit: 3.0, spaceLimit: 512,
        description: 'Find the shortest transformation sequence from beginWord to endWord.',
        inputFormat: 'First line: beginWord endWord\nSecond line: n\nNext n lines: words in dictionary',
        outputFormat: 'Length of shortest chain, or 0 if none',
        constraints: '1 ≤ wordList.length ≤ 5000\n1 ≤ word.length ≤ 10',
        examples: [{ input: 'hit cog\n6\nhot dot dog lot log cog', output: '5', explanation: 'hit→hot→dot→dog→cog' }],
        testCases: [],
        languages: ['CPP', 'JAVA', 'PYTHON'],
        multipleSolution: false,
        validatorCode: '',
      },
    ],
  },
  {
    id: 2,
    title: 'Apex Week',
    startDate: '2025-01-20',
    startTime: '10:00',
    active: true,
    displaySection: 'upcoming',
    scoringSystem: 'full',
    problems: [],
  },
  {
    id: 3,
    title: 'Elite Week',
    startDate: '2025-02-03',
    startTime: '10:00',
    active: false,
    displaySection: 'hidden',
    scoringSystem: 'time',
    problems: [],
  },
]

export const initialEvents = [
  {
    id: 1,
    title: 'Spring Contest 2025',
    startDate: '2025-03-15',
    startTime: '14:00',
    durationHours: 3,
    status: 'live',
    problems: [],
  },
  {
    id: 2,
    title: 'DSA Championship',
    startDate: '2025-04-20',
    startTime: '10:00',
    durationHours: 5,
    status: 'upcoming',
    problems: [],
  },
]

export const SCORING_SYSTEMS = {
  full: { label: 'Full Score', desc: 'Pass all test cases for full points, else 0' },
  partial: { label: 'Partial Scoring', desc: 'Score proportional to test cases passed' },
  time: { label: 'Time Decay', desc: 'Score decreases the longer a participant takes' },
}
